
Database: boltdb

Compute: local

EventWriters: 
  - boltdb
  - log

Server:
  # Hostname of the Funnel server.
  HostName: localhost

  # Port used for HTTP communication and the web dashboard.
  HTTPPort: 8010

  # Port used for RPC communication.
  RPCPort: 9090

RPCClient:
  # RPC server address 
  ServerAddress: localhost:9090

  # Credentials for Basic authentication for the server APIs using a password.
  # If used, make sure to properly restrict access to the config file
  # (e.g. chmod 600 funnel.config.yml)
  # User: funnel
  # Password: abc123

  # connection timeout.
  Timeout: 60s

  # The maximum number of times that a request will be retried for failures.
  # Time between retries follows an exponential backoff starting at 5 seconds
  # up to 1 minute
  MaxRetries: 10


Worker:
  # Files created during processing will be written in this directory.
  WorkDir: /data/funnel-work-dir
 
BoltDB:
  # Path to the database file
  Path: /data/funnel-work-dir/funnel.db

LocalStorage:
  # Whitelist of local directory paths which Funnel is allowed to access.
  AllowedDirs:
    - ./

GenericS3: # CHANGE ME
  - Disabled: false
    Endpoint: "http://s3:9000"
    Key: "access"
    Secret: "secretkey"

# Amazon S3 is enabled by default, so we need to set it up to disable it
# and not conflict with our S3
AmazonS3:
  Disabled: true

